### PR TITLE
Update lib.rs to support more keywords

### PR DESCRIPTION
**Pull request by liminchen**

### CODE REVIEW

**Comment by yannickseurin** [comment]
Thanks for the suggestion! I'm a bit reluctant to add more and more environments hardcoded in the lib, if people actually start using it I think the right way to proceed is to allow to have user-defined environments through the `book.toml`.
This shouldn't be overly complicated, I'll try to implement this in the coming days.

**Comment by liminchen** [comment]
Thanks a lot! Yes, enabling user-defined environments will be super helpful!

**Comment by yannickseurin** [comment]
FYI, I've added the feature in v0.2.0 of the crate. See the updated README to see how to configure new environments.

I haven't tested it a lot, happy to get your feedback if you play with it!

**Comment by liminchen** [comment]
Thank you so much! We've started using it in our project, and so far it works nicely!

**Pull request closed without merging**
